#!/bin/bash

# Arch Linux USB Creator
# Copyright (C) 2014  Branislav Holý <branoholy@gmail.com>
#
# This file is part of Arch Linux USB Creator.
#
# Arch Linux USB Creator is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Arch Linux USB Creator is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Arch Linux USB Creator.  If not, see <http://www.gnu.org/licenses/>.

echo "Arch Linux USB Creator"

if [ -n "$1" ]; then
	if [ ! -b "$1" ]; then
		echo "Error: Partition option is not set to block device."
		exit
	fi
else
	echo "Error: Missing partition option (see README.md file)!"
	exit
fi

partition=$1
device=${partition:0: -1}
partitionNumber=${partition: -1}

if [ -n "$2" ]; then
	if [ -f "$2" ]; then
		download=false
		isoPath=$2
	elif [ -d "$2" ]; then
		download=true
		downloadDir=$2
	else
		echo "Error: Wrong path to ISO or to download directory!"
		exit
	fi
else
	download=true
	downloadDir=/tmp
fi

. config.conf

if $download; then
	echo "Downloading the latest Arch Linux ISO..."

	if [ -z "$mirror" ]; then
		echo "Error: You have to set mirror variable in config.conf file (see README.md file)!"
		exit
	fi

	cwd=`pwd`
	cd "$downloadDir"

	mirrorDir="$mirror/iso/latest"

	echo
	wget $mirrorDir -O archlinux-iso-index.html
	isoName=`sed "s/.*\(archlinux-[0-9\.]\+-dual\.iso\).*/\1/" archlinux-iso-index.html | grep dual.iso | tail -1`
	rm archlinux-iso-index.html

	wget "$mirrorDir/$isoName" -O "$isoName"
	wget "$mirrorDir/sha1sums.txt" -O archlinux-iso-sha1sums.txt

	cat archlinux-iso-sha1sums.txt | grep dual.iso | sha1sum -c --status
	if [ "$?" == "0" ]; then
		isoPath="$downloadDir/$isoName"
		rm archlinux-iso-sha1sums.txt
		cd "$cwd"
	else
		echo "Error: sha1sum does not match!"
		rm archlinux-iso-sha1sums.txt
		rm "$isoName"
		exit
	fi
fi

echo "Mounting ISO and USB..."

mkdir -p /mnt/archlinux-iso
mount -o loop,ro "$isoPath" /mnt/archlinux-iso

mkdir -p /mnt/archlinux-usb
mount "$partition" /mnt/archlinux-usb

echo "Copying files to USB..."

cp -a /mnt/archlinux-iso/* /mnt/archlinux-usb

sed -i "s|label=ARCH_.*|device=/dev/disk/by-uuid/$(blkid -o value -s UUID $partition)|" /mnt/archlinux-usb/arch/boot/syslinux/archiso_sys{32,64}.cfg /mnt/archlinux-usb/loader/entries/archiso-x86_64.conf

cp -r "$syslinux"/*.c32 /mnt/archlinux-usb/arch/boot/syslinux
$extlinux --install /mnt/archlinux-usb/arch/boot/syslinux

sync
umount /mnt/archlinux-iso
umount /mnt/archlinux-usb
rmdir /mnt/archlinux-iso
rmdir /mnt/archlinux-usb

if $download; then
	rm "$isoPath"
fi

sfdisk -A$partitionNumber $device
dd bs=440 count=1 conv=notrunc if="$syslinux/mbr.bin" of=$device

echo "Arch Linux USB Creator: Done"

